CREATE TABLE APP_ROLE (
    USER_ROLE VARCHAR2(20)  PRIMARY KEY,
    IS_TRAINING_REQUIRED CHAR(1) default 'Y' not null constraint ROLE_TRAINING_REQUIRED_CHK check ( IS_TRAINING_REQUIRED IN ('N', 'Y'))
);